#!/usr/bin/env sh

# Retrieve the current preview offset.
offset="$(cat "$LF_SCROLLINGPREVIEW_TEMPDIR/offset")"

# Apply offset during the generation of the preview.
case "$(basename "$1" | tr '[:upper:]' '[:lower:]')" in
*)
	# Use awk to select a page range.	
	awk "NR > ${offset}-1" "$1"
	;;
esac
